### PR TITLE
Fixed the build

### PR DESCRIPTION
**Pull request by jsight**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-quickstarts-master/5/
Test FAILed.

**Comment by sgilda** [comment]
@jsight : Thanks for doing this! 

I don't get the StackOverflowError, but I do get an assertion failure:

-------------------------------------------------------------------------------
Test set: org.jboss.windup.qs.rules.EjbBeanUtilsAsyncUsageRuleProviderTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 36.568 sec <<< FAILURE!
testRules(org.jboss.windup.qs.rules.EjbBeanUtilsAsyncUsageRuleProviderTest)  Time elapsed: 7.867 sec  <<< FAILURE!
java.lang.AssertionError: xmlRuleHintFound
	at org.junit.Assert.fail(Assert.java:88)

**Comment by sgilda** [comment]
@jsight : Is it okay if I go ahead and merge this one and we can address the test failure later?

**Comment by jsight** [comment]
Yes

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
