### PR TITLE
T617 Upgrade Forge and Furnace, the really latest ones

### PR DESCRIPTION
**Pull request by OndraZizka**
See https://github.com/windup/windup/pull/1084 and https://github.com/windup/windup-web/pull/272

### CODE REVIEW

**Comment by mareknovotny** [comment]
Will you fix [ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /var/lib/jenkins/workspace/windup-core-PR-dependents-check/windup-quickstarts/victi.ms/src/test/java/org/jboss/windup/qs/victims/test/VictimsRulesetTest.java:[15,42] cannot find symbol

**Comment by mareknovotny** [comment]
retest

**Comment by mareknovotny** [comment]
reference also on dependent CI job for https://github.com/windup/windup/pull/1084 at http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/windup-core-PR-dependents-check/1425/consoleText

**Comment by mareknovotny** [comment]
I sent PR for you to fix it - remove not used outdated class imports https://github.com/OndraZizka/windup-quickstarts/pull/2

**Comment by OndraZizka** [comment]
Thanks :)

**Pull request merged**
